# Generated by Django 5.2.17 on 2026-09-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=80, verbose_name='Telegram')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(blank=True, help_text='Какая машина или услуга интересует', max_length=255, verbose_name='Источник (техника / услуга)')),
                ('form_type', models.CharField(choices=[('general', 'Оставить заявку'), ('vehicle', 'Запросить эту машину'), ('calculator', 'Рассчитать выгоду'), ('callback', 'Заказать звонок')], default='general', max_length=20, verbose_name='Тип формы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('page_url', models.CharField(blank=True, max_length=255, verbose_name='Страница')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Данные калькулятора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
