# Generated by Django 5.2.17 on 2026-09-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Слаг')),
                ('is_flagship', models.BooleanField(default=False, verbose_name='Флагман (FAW)')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Кратко')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Слаг')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='Слаг')),
                ('condition', models.CharField(choices=[('new', 'Новая'), ('used', 'Проверенный б/у')], default='new', max_length=12, verbose_name='Состояние')),
                ('availability', models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ')], default='in_stock', max_length=12, verbose_name='Наличие')),
                ('price_usd', models.PositiveIntegerField(verbose_name='Цена, USD')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег, км')),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.')),
                ('wheel_formula', models.CharField(blank=True, max_length=16, verbose_name='Колёсная формула')),
                ('payload', models.CharField(blank=True, max_length=80, verbose_name='Грузоподъёмность / ССУ')),
                ('engine', models.CharField(blank=True, max_length=120, verbose_name='Двигатель')),
                ('gearbox', models.CharField(blank=True, max_length=80, verbose_name='КПП')),
                ('fuel', models.CharField(blank=True, default='Дизель', max_length=40, verbose_name='Топливо')),
                ('gvw', models.CharField(blank=True, max_length=40, verbose_name='Полная масса')),
                ('short_specs', models.CharField(blank=True, max_length=220, verbose_name='Краткие ТТХ (карточка)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('extra_features', models.TextField(blank=True, verbose_name='Дополнительно')),
                ('main_image', models.ImageField(blank=True, upload_to='vehicles/', verbose_name='Главное фото')),
                ('use_placeholder', models.BooleanField(default=True, help_text='Показывает подпись, что фото с площадки появится позже.', verbose_name='Плейсхолдер «фото с площадки»')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=True, verbose_name='На главной')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='catalog.category', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Единица техники',
                'verbose_name_plural': 'Техника',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Подпись')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.vehicle', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
